version: '3.1'

services:
  postgresql:
    image: postgres:alpine3.14
    ports:
      - 5432:5432
    
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: "test_db"
    hostname: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4:5.6
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgresql

  gcc:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/workspace

    depends_on:
      - postgresql
      - pgadmin