name: doc_build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    working_directory: /docs

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      
      - uses: actions/setup-python@v1
        with:
          python-verison: 3.9
      - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      -run: |
        git config --global user.name "github-actions"
        git config --global user.email "<>"
        git clone git@github.com:${GITHUB_REPOSITORY}.git -b gh-pages build/html
        ls -1 | xargs rm -rf
        make html
        cd build/html
        touch .nojekyll
        git add -A
        git commit -m "deploy documents by github-actions"
        git push git@github.com:${GITHUB_REPOSITORY}.git main:gh-pages