name: doc_build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "main"
      
      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-verison: 3.9
      
      - name: Install sphinx
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: docs/build/html

      - name: deploy
        working-directory: docs
        run: |
          ls build/html/* -d -1 | xargs rm -rf
          make html
          cd build/html
          touch .nojekyll
          git add -A
          git commit -m "deploy documents by github-actions"
          git push git@github.com:${GITHUB_REPOSITORY}.git main:gh-pages