name: gcc

on:
  push:
    branches-ignore:
      - gh-pages

env:
  BUILD_TYPE: Release
  CC: gcc-11
  CXX: g++-11

jobs:
  compile_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/compile_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/compile_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Run
        working-directory: ${{github.workspace}}/tests/compile_tests/build
        run: ./query_scalar && ./query_vector && ./model_query

  sqlite3-tests:
    runs-on: ubuntu-latest
    needs: [compile_tests]
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run integrated tests
        timeout-minutes: 5
        working-directory: ${{github.workspace}}/tests/integrated_tests/build
        run: ./arcxx_IT

  postgresql-tests:
    runs-on: ubuntu-latest
    needs: [compile_tests]
    strategy:
      matrix:
        build_type: [Debug, Release]
    services:
      postgres:
        image: postgres:alpine3.14
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
          POSTGRES_DB: "test_db"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DTARGET_SQL=PostgreSQL .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Run integrated tests
        timeout-minutes: 5
        working-directory: ${{github.workspace}}/tests/integrated_tests/build
        run: ./arcxx_IT


  benchmarks:    
    runs-on: ubuntu-latest
    needs: [sqlite3-tests, postgresql-tests]
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Run benchmarks
        timeout-minutes: 5
        working-directory: ${{github.workspace}}/tests/benchmarks/build
        run: ./arcxx_bench