name: MSVC

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  compile_tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/compile_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/compile_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

  sqlite3-tests:
    runs-on: windows-2022
    needs: [compile_tests]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Install packages
        run: |
          vcpkg integrate install
          vcpkg update
          vcpkg install sqlite3:x64-windows catch2:x64-windows

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Run integrated tests
        working-directory: ${{github.workspace}}/tests/integrated_tests/build/${{env.BUILD_TYPE}}
        run: ./arcxx_IT.exe

  postgresql-tests:
    runs-on: windows-2022
    needs: [compile_tests]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Start PostgreSQL server
        run: |
          &"$env:PGBIN/pg_ctl.exe" start
          &"$env:PGBIN/createdb.exe" test_db

      - name: Install packages
        run: |
          vcpkg integrate install
          vcpkg update
          vcpkg install libpq:x64-windows catch2:x64-windows

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTARGET_SQL=PostgreSQL -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Run integrated tests
        working-directory: ${{github.workspace}}/tests/integrated_tests/build/${{env.BUILD_TYPE}}
        run: ./arcxx_IT.exe

  benchmarks:
    runs-on: windows-2022
    needs: [sqlite3-tests, postgresql-tests]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Install packages
        run: |
          vcpkg integrate install
          vcpkg update
          vcpkg install catch2:x64-windows

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake .

      - name: Build
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Run benchmarks
        working-directory: ${{github.workspace}}/tests/benchmarks/build/${{env.BUILD_TYPE}}
        run: ./arcxx_bench.exe
