name: MSVC

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  sqlite3-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.3

      - name: Install packages
        run: nuget install sqlite3

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run integrated tests
        working-directory: ${{github.workspace}}/tests/integrated_tests/build
        run: ./active_record_IT.exe

  benchmarks:    
    runs-on: windows-latest
    needs: [sqlite3-tests]
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.3

      - name: Install packages
        run: nuget install sqlite3

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run benchmarks
        working-directory: ${{github.workspace}}/tests/benchmarks/build
        run: ./active_record_bench.exe