name: test

on:
  push:
    branches-ignore:
      - gh-pages

env:
  BUILD_TYPE: Release
  CC: gcc-11
  CXX: g++-11

jobs:
  sqlite3-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run integrated tests
        working-directory: ${{github.workspace}}/tests/integrated_tests/build
        run: ./active_record_IT

  postgresql-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine3.14
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
          POSTGRES_DB: "test_db"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get install -y libpq-dev software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTARGET_SQL=PostgreSQL .

      - name: Build
        working-directory: ${{github.workspace}}/tests/integrated_tests
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run integrated tests
        working-directory: ${{github.workspace}}/tests/integrated_tests/build
        run: ./active_record_IT


  benchmarks:    
    runs-on: ubuntu-latest
    needs: [sqlite3-tests, postgresql-tests]
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11

      - name: Configure CMake
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

      - name: Build
        working-directory: ${{github.workspace}}/tests/benchmarks
        run: cmake --build build --config ${{env.BUILD_TYPE}} -j2

      - name: Run benchmarks
        working-directory: ${{github.workspace}}/tests/benchmarks/build
        run: ./active_record_bench