name: test

on:
  push:
    branches-ignore:
      - gh-pages

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: gcc:11.2.0

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/test/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/test/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        working-directory: ${{github.workspace}}/test/build
        run: ctest -V